# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\"\x92\x05\n\x12TransactionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x18\n\x10transaction_type\x18\x02 \x01(\t\x12\x1d\n\x15transaction_timestamp\x18\x03 \x01(\t\x12\x14\n\x0c\x61mount_value\x18\x04 \x01(\x01\x12\x17\n\x0f\x61mount_currency\x18\x05 \x01(\t\x12\x1a\n\x12sender_customer_id\x18\x06 \x01(\t\x12\x19\n\x11sender_account_id\x18\x07 \x01(\t\x12\x1b\n\x13sender_account_type\x18\x08 \x01(\t\x12\x19\n\x11sender_kyc_status\x18\t \x01(\t\x12\x1f\n\x17sender_account_age_days\x18\n \x01(\x05\x12\x14\n\x0csender_state\x18\x0b \x01(\t\x12\x13\n\x0bsender_city\x18\x0c \x01(\t\x12\x1d\n\x15sender_txn_count_1min\x18\r \x01(\x05\x12\x1e\n\x16sender_txn_count_10min\x18\x0e \x01(\x05\x12\x1a\n\x12sender_amount_24hr\x18\x0f \x01(\x01\x12\x13\n\x0b\x64\x65vice_type\x18\x10 \x01(\t\x12\x11\n\tdevice_os\x18\x11 \x01(\t\x12\x13\n\x0b\x61pp_version\x18\x12 \x01(\t\x12\x0f\n\x07ip_risk\x18\x13 \x01(\t\x12\x15\n\rreceiver_type\x18\x14 \x01(\t\x12\x15\n\rreceiver_bank\x18\x15 \x01(\t\x12\x19\n\x11merchant_category\x18\x16 \x01(\t\x12\x1b\n\x13merchant_risk_level\x18\x17 \x01(\t\x12\x16\n\x0epayment_method\x18\x18 \x01(\t\x12\x1a\n\x12\x61uthorization_type\x18\x19 \x01(\t\"\xee\x01\n\rFraudResponse\x12\x10\n\x08is_fraud\x18\x01 \x01(\x08\x12\x12\n\nrisk_score\x18\x02 \x01(\x01\x12#\n\x1b\x66raud_reason_unusual_amount\x18\x03 \x01(\x08\x12)\n!fraud_reason_geo_distance_anomaly\x18\x04 \x01(\x08\x12\"\n\x1a\x66raud_reason_high_velocity\x18\x05 \x01(\x08\x12\x16\n\x0e\x66raud_severity\x18\x06 \x01(\t\x12\x12\n\nflag_color\x18\x07 \x01(\t\x12\x17\n\x0freason_of_fraud\x18\x08 \x01(\t2k\n\x15\x46raudDetectionService\x12R\n\x0b\x44\x65tectFraud\x12#.fraud_detection.TransactionRequest\x1a\x1e.fraud_detection.FraudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=43
  _globals['_TRANSACTIONREQUEST']._serialized_end=701
  _globals['_FRAUDRESPONSE']._serialized_start=704
  _globals['_FRAUDRESPONSE']._serialized_end=942
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=944
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=1051
# @@protoc_insertion_point(module_scope)
